### PR TITLE
[TASK] Push code changes to php7 branch

### PR DESCRIPTION
**Pull request by S-mardii**

### CODE REVIEW

**Comment by S-mardii** [comment]
@EricSoroos the conflict has been resolved. Now the code is ready for reviewing.

**Comment by S-mardii** [comment]
@EricSoroos Once you pull the code to the pre-production site, I would test uploading the content before we could push it to Production

**Comment by EricSoroos** [comment]
@S-mardii Code is on preprod.

**Comment by S-mardii** [comment]
Thank you @EricSoroos for your support.

By the way, I could not login the WP preprod with my account. Could you help check or reset the password for my account `mardysam` on preprod?

**Comment by S-mardii** [comment]
@EricSoroos as the day that we would have to demo the web page to the stakeholder is on 23rd February, I would like to follow up for your support on this issue.

**Comment by S-mardii** [comment]
@EricSoroos A few changes has been pushed to `php7`, so please pull the new code changes to the PreProd

**Comment by S-mardii** [comment]
> Thank you @EricSoroos for your support.
> 
> By the way, I could not login the WP preprod with my account. Could you help check or reset the password for my account `mardysam` on preprod?

FYI, I can access the admin of WP on preprod normally now.

**Comment by EricSoroos** [comment]
I've pulled the changes to preprod

**Pull request merged**
