### PR TITLE
[TASK] Add summary widget to right sidebar

### PR DESCRIPTION
**Pull request by S-mardii**
- Add `od_summary` widget to the sidebar
- change `class="content"` to `id="content"`

### CODE REVIEW

**Comment by S-mardii** [comment]
Fixed #230

**Comment by EricSoroos** [comment]
On PP, let me know for prod @S-mardii

**Comment by S-mardii** [comment]
Thank you @EricSoroos. Tested on PP and it looks good. Please pull the code to Prod.

Link: https://pp.opendevelopmentcambodia.net/profiles/access-to-public-service/civil-status/

image

**Comment by EricSoroos** [comment]
It's up on prod.

**Comment by S-mardii** [comment]
Thank you @EricSoroos

**Pull request merged**
